server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_crud
    username: root
    password: admin12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  name: jwt-auth
